---
drake_cache: ".lifeInfo"
---

```{r makecondition}
library(dplyr)
library(htmltools)
library(econR)
.GlobalEnv$web <- econR::Web()
web$foldername="docs" # output folder name
web$html_filename <- "lifeInfo.html"

```

## SASS

```{r makecondition}
library(sass)
my_sass <- sass(
  sass_file("sass_demo.scss"))
```


```{r tag_sass}
tag_sass <- tags$style(
  my_sass
)
```

## buses

```{r buses} 
tagList(
  tags$div(
  class="valign-wrapper",
  tags$i(class="material-icons","directions_bus"), "916"
),
tags$div(
  class="valign-wrapper less5mins",
  tags$a(class="btn-floating pulse red",
       tags$i(class="material-icons","directions_bus")),
 "916"),
tags$div(
  class="valign-wrapper between5and10",
  tags$i(class="material-icons","directions_bus"), "916"
),
tags$div(
  class="valign-wrapper more10mins",
  tags$i(class="material-icons","directions_bus"), "916"
)
)


```


### BUS js

```{r busJs}
htmltools::includeScript("js/bus.js")
```

### SHA js

```{r sha_js}
sha_js <- 
  htmltools::htmlDependency(
    name="sha",
    version="3.2.0",
    src=c(href = "https://cdnjs.cloudflare.com"),
    # to use the same library here must use href, not filepath; otherwise, the current jquery system will be removed.
    script = c("ajax/libs/jsSHA/3.2.0/sha.min.js")
  )
```


### Body Tags

```{r bodyTags}
bodyTags <- {
  htmltools::tagList(
    tags$div(class="container",
             tags$div(class="row",
                      buses
                      )),
    tag_sass,
    busJs
  )
}
```


## HTML Structure

```{r html_placeholder}
html_placeholder <- tags$html(
  tags$head(
    do.call(htmltools::tagList, headTags),
    tags$meta(
      name="viewport",
      content="width=device-width, initial-scale=1.0"
    )
  ),
  tags$body(
    do.call(htmltools::tagList, bodyTags)
  )
)
```

## Dependencies

### Head Tags

```{r headTags}
headTags <- {
  htmltools::tagList(
    htmltools::tags$link(
      href="https://fonts.googleapis.com/icon?family=Material+Icons",
      rel="stylesheet"
    )
  )
}
```

### Define dependency

```{r myDependency}
myDependency <- htmltools::htmlDependency(
  name="myown",
  version="1.0",
  src=c(filepath=web$cssJsPath),
  stylesheet = "css/mystyle.css",
  script = "js/mydesign.js",
  head = '<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Noto+Sans+TC">
'
)
```

  * If src is in other path, use `web$config_cssJsPath("your_path")` in **makecondition** -- no need to change `web$cssJsPath` (it will change accordingly).

```{html jquery}
<script src="https://code.jquery.com/jquery-3.6.0.js" integrity="sha256-H+K7U5CnXl1h5ywQfKtSj8PCmoN9aaq30gDh27Xc0jk=" crossorigin="anonymous"></script>
```

```{r new_jquery}
new_jquery <- 
  htmltools::htmlDependency(
    name="jquery",
    version="3.6.0",
    src=c(href = "https://code.jquery.com/"),
    # to use the same library here must use href, not filepath; otherwise, the current jquery system will be removed.
    script = c("jquery-3.6.0.js")
  )
```

```{r local_jquery}
local_jquery <- 
  htmltools::htmlDependency(
    name="jquery",
    version="3.5.1",
    src=c(href = "lib/jquery-3.5.1"),
    # to use the same library here must use href, not filepath; otherwise, the current jquery system will be removed.
    script = c("jquery.min.js")
  )
```

### Attach dependency


```{r html_complete}
html_complete <- 
  htmltools::tagList(
    html_placeholder,
    web$htmlDependencies$materialise(),
    local_jquery, 
    myDependency,
    new_jquery,
    sha_js
  )
```

  * If not using jquery from htmlwidgets, replace `local_jquery` with `web$htmlDependencies$jquery()`


## Save

```{r save_html}
htmltools::save_html(
  html_complete, 
  file = web$output_filepath(),
  libdir="lib"
)
```

## Browse

```{r}
web$browse()
```





## JS


<!--JS end-->
